### PR TITLE
Issue 1: Fix --existing-config option with function

### PR DESCRIPTION
**Pull request by ghost**
Pull request for issue https://github.com/php-taskman/drupal/issues/1

### CODE REVIEW

**Review by drupol — APPROVED** [review]
I trust you on this :-)

**Comment by drupol** [comment]
Pushed on 0.x as well !

**Comment by drupol** [comment]
0.1.20 and 1.0.2 released with this PR ! \o/

Thanks mate!

**Comment by ghost** [comment]
Thx Pol, we should also have a talk about maybe setting up a travis for testing the commands. Then we can trust tests instead of me ;)

**Comment by drupol** [comment]
Definitely... I know that tests are missing in here, I had in mind to use codeception for testing, what do you think ?

**Comment by ghost** [comment]
I've never used codeception.  I was thinking about having two composer.json files for testing with a full drupal installation (7.x and 8.x) and run the commands on it.

**Comment by drupol** [comment]
It's very nice for testing CLI stuff.

Based on PhpUnit, it's quite easy to include in the project (only 1 dependency).

Documentation is very nice and it has a lot of features.

Have a look at:
* https://github.com/drupol/phpcsfixer-configs-drupal/blob/master/tests/functional/Scenario0Cept.php
* https://github.com/drupol/composer-package-artifacts/blob/master/tests/functional/Scenario0Cept.php

See the quick start: https://codeception.com/quickstart

**Comment by aritomelo** [comment]
Thx I will have a look asap.

**Pull request merged**
